apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: kafka-producer
        image: yuchun33/kafka-producer:latest
        command: ["python", "-u", "src/main.py", "--bootstrap-servers", "kafka-headless:9092"]
